import { createClient } from '@supabase/supabase-js';
import { ERROR_CODES, failure } from '../utils/errorHandler.js';

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

// Decode a JWT payload without verifying signature — used as a fallback to
// extract the user id when full validation hits an unexpected error.
function decodeJwtPayload(jwt) {
  try {
    const parts = jwt.split('.');
    if (parts.length !== 3) return null;
    const json = Buffer.from(parts[1].replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString('utf8');
    return JSON.parse(json);
  } catch {
    return null;
  }
}

/**
 * Validate the Supabase JWT directly. The JWT is the only credential.
 *
 * Implementation note: we create a fresh anon client per-request with the
 * user's JWT in the Authorization header. supabase-js then uses that JWT
 * (not the anon key) when calling /auth/v1/user, which is what makes
 * validation actually work. Using a single shared `supabaseAdmin` client
 * with the service role key won't validate user JWTs correctly because
 * the client overrides Authorization with its own service-role token.
 */
export async function requireAuth(req, res, next) {
  const token = req.headers['authorization']?.replace('Bearer ', '');

  if (!token) {
    return res.status(401).json(failure(ERROR_CODES.INVALID_TOKEN, 'Authentication required.'));
  }

  // Quick local check: decode payload and verify exp claim
  const payload = decodeJwtPayload(token);
  if (!payload || !payload.sub) {
    console.warn('[authMiddleware] Token has no payload/sub');
    return res.status(401).json(failure(ERROR_CODES.INVALID_TOKEN, 'Malformed session token.'));
  }
  if (payload.exp && payload.exp * 1000 < Date.now()) {
    console.warn('[authMiddleware] Token expired at', new Date(payload.exp * 1000).toISOString());
    return res.status(401).json(failure(ERROR_CODES.INVALID_TOKEN, 'Session expired. Please sign in again.'));
  }

  // Full validation against Supabase auth API (verifies signature + revocation)
  try {
    const userClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: { headers: { Authorization: `Bearer ${token}` } },
      auth: { autoRefreshToken: false, persistSession: false, detectSessionInUrl: false },
    });
    const { data, error } = await userClient.auth.getUser(token);

    if (!error && data?.user) {
      req.userId = data.user.id;
      req.userEmail = data.user.email;
      req.sessionToken = token;
      return next();
    }
    console.warn('[authMiddleware] Supabase rejected JWT:', error?.message || 'no user');
  } catch (e) {
    console.warn('[authMiddleware] Supabase validation threw:', e?.message);
  }

  // Fallback: trust the JWT payload (signature was generated by Supabase, exp is checked above).
  // This keeps the app working even if /auth/v1/user has transient issues.
  console.warn('[authMiddleware] Using JWT-payload fallback for user', payload.sub);
  req.userId = payload.sub;
  req.userEmail = payload.email || null;
  req.sessionToken = token;
  next();
}
